
server:
  port: 8083
resilience4j:
  circuitbreaker:
    instances:
      matriculaCb:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  timelimiter:
    instances:
      matriculaTl:
        timeoutDuration: 2s
  bulkhead:
    instances:
      matriculaBh:
        maxThreadPoolSize: 10
        coreThreadPoolSize: 4
        queueCapacity: 10
